uploads = []
generated = []

[[outputs]]
id = "BHYPGAwIhCcrNkC7wB3-B"
uri = "file://assets/images/logo-source.svg"
type = "image"
title = "Logo (SVG)"

[[outputs]]
id = "xeQcJe-ApemkmvkS4ySI8"
uri = "file://docs/libdivecomputer-shearwater-mapping.md"
type = "text"
title = "Same doc (Markdown source)"

[[outputs]]
id = "iXXQjQ6b6FwPnhqUP8dTd"
uri = "file://docs/libdivecomputer-shearwater-mapping.pdf"
type = "pdf"
title = "Shearwater (Perdix) → Erebus Data Mapping (PDF)"

[[outputs]]
id = "M3nE3US2tOkb_Z1HOBtIN"
uri = "file://erebus-project.zip"
type = "unspecified"
title = "Erebus Project (full source)"
