import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DivePlanResult, DivePlanSettings, GasMix, DiveSegment, DecoStop, GasConsumption } from './divePlanner';

interface DivePlanPdfInput {
  result: DivePlanResult;
  settings: DivePlanSettings;
  depth: number;
  bottomTime: number;
  gases: GasMix[];
}

function formatDuration(minutes: number): string {
  const mins = Math.floor(minutes);
  const secs = Math.round((minutes - mins) * 60);
  return secs > 0 ? `${mins}:${secs.toString().padStart(2, '0')}` : `${mins}`;
}

function formatGas(gas: GasMix): string {
  if (gas.hePercent > 0) {
    return `${gas.o2Percent}/${gas.hePercent}`;
  } else if (gas.o2Percent === 21) {
    return 'Air';
  } else {
    return `EAN${gas.o2Percent}`;
  }
}

function drawDiveProfile(doc: jsPDF, result: DivePlanResult, x: number, y: number, width: number, height: number) {
  const segments = result.segments;
  if (segments.length === 0) return;
  
  const maxDepth = Math.max(...segments.map(s => Math.max(s.startDepth, s.endDepth)));
  const totalTime = segments[segments.length - 1].runTime;
  
  const padding = { top: 15, right: 10, bottom: 20, left: 25 };
  const chartW = width - padding.left - padding.right;
  const chartH = height - padding.top - padding.bottom;
  
  doc.setDrawColor(180);
  doc.setLineWidth(0.3);
  doc.rect(x + padding.left, y + padding.top, chartW, chartH);
  
  doc.setFontSize(7);
  doc.setTextColor(100);
  
  doc.text('0m', x + padding.left - 3, y + padding.top + 3, { align: 'right' });
  doc.text(`${Math.round(maxDepth)}m`, x + padding.left - 3, y + padding.top + chartH, { align: 'right' });
  
  doc.text('0', x + padding.left, y + padding.top + chartH + 8, { align: 'center' });
  doc.text(`${Math.round(totalTime)}min`, x + padding.left + chartW, y + padding.top + chartH + 8, { align: 'center' });
  
  doc.setFontSize(6);
  doc.text('Depth', x + 5, y + padding.top + chartH / 2, { angle: 90 });
  doc.text('Time', x + padding.left + chartW / 2, y + height - 3, { align: 'center' });
  
  doc.setDrawColor(0, 100, 180);
  doc.setLineWidth(0.8);
  
  let prevX = x + padding.left;
  let prevY = y + padding.top;
  
  segments.forEach((seg, i) => {
    const startTimeRatio = (seg.runTime - seg.duration) / totalTime;
    const endTimeRatio = seg.runTime / totalTime;
    const startDepthRatio = seg.startDepth / maxDepth;
    const endDepthRatio = seg.endDepth / maxDepth;
    
    const x1 = x + padding.left + startTimeRatio * chartW;
    const y1 = y + padding.top + startDepthRatio * chartH;
    const x2 = x + padding.left + endTimeRatio * chartW;
    const y2 = y + padding.top + endDepthRatio * chartH;
    
    if (i === 0) {
      prevX = x1;
      prevY = y1;
    }
    
    doc.line(prevX, prevY, x1, y1);
    doc.line(x1, y1, x2, y2);
    
    prevX = x2;
    prevY = y2;
  });
  
  doc.setDrawColor(0, 150, 0);
  doc.setLineWidth(0.3);
  const surfaceLine = y + padding.top;
  doc.setLineDashPattern([2, 2], 0);
  doc.line(x + padding.left, surfaceLine, x + padding.left + chartW, surfaceLine);
  doc.setLineDashPattern([], 0);
}

export function generateDivePlanPdf(input: DivePlanPdfInput): void {
  const { result, settings, depth, bottomTime, gases } = input;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  
  doc.setFillColor(0, 80, 130);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setTextColor(255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('DIVE PLAN', margin, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const date = new Date().toLocaleDateString('en-US', { 
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' 
  });
  doc.text(date, margin, 28);
  
  doc.setTextColor(200);
  doc.setFontSize(8);
  doc.text('Generated by Erebus Dive Planner', pageWidth - margin, 28, { align: 'right' });
  
  let yPos = 45;
  
  doc.setTextColor(0, 80, 130);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('DIVE SUMMARY', margin, yPos);
  yPos += 8;
  
  const summaryData = [
    ['Maximum Depth', `${depth} ${settings.units === 'metric' ? 'm' : 'ft'}`],
    ['Bottom Time', `${bottomTime} min`],
    ['Total Runtime', `${formatDuration(result.totalRunTime)} min`],
    ['Deco Stops', result.decoStops.length > 0 ? `${result.decoStops.length} stops` : 'None (NDL dive)'],
    ['CNS Oxygen', `${Math.round(result.cns || 0)}%`],
    ['OTU', `${Math.round(result.otu || 0)} units`],
  ];
  
  autoTable(doc, {
    startY: yPos,
    head: [],
    body: summaryData,
    theme: 'plain',
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 2 },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 40 },
      1: { cellWidth: 50 }
    },
    tableWidth: 90,
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setTextColor(0, 80, 130);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('DIVE PROFILE', margin, yPos);
  yPos += 5;
  
  drawDiveProfile(doc, result, margin, yPos, contentWidth, 60);
  yPos += 70;
  
  if (result.decoStops.length > 0) {
    doc.setTextColor(0, 80, 130);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('DECOMPRESSION SCHEDULE', margin, yPos);
    yPos += 5;
    
    let cumulativeRuntime = 0;
    const decoData = result.decoStops.map((stop, i) => {
      cumulativeRuntime += stop.duration;
      return [
        `${i + 1}`,
        `${stop.depth} ${settings.units === 'metric' ? 'm' : 'ft'}`,
        `${formatDuration(stop.duration)} min`,
        formatGas(stop.gasMix),
        `${Math.round(stop.ceiling)} ${settings.units === 'metric' ? 'm' : 'ft'}`
      ];
    });
    
    autoTable(doc, {
      startY: yPos,
      head: [['#', 'Depth', 'Duration', 'Gas', 'Ceiling']],
      body: decoData,
      theme: 'striped',
      margin: { left: margin, right: margin },
      headStyles: { fillColor: [0, 80, 130], fontSize: 9 },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 30 },
        2: { cellWidth: 30 },
        3: { cellWidth: 30 },
        4: { cellWidth: 30 }
      },
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  doc.setTextColor(0, 80, 130);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('GAS CONFIGURATION', margin, yPos);
  yPos += 5;
  
  const gasData = gases.map(gas => [
    gas.name,
    formatGas(gas),
    `${gas.switchDepth !== null ? gas.switchDepth + (settings.units === 'metric' ? 'm' : 'ft') : '-'}`,
    `MOD: ${gas.modPpo2_14} ${settings.units === 'metric' ? 'm' : 'ft'}`,
    `${gas.cylinderVolume}L @ ${gas.fillPressure}bar`
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['Name', 'Mix', 'Switch', 'MOD (1.4)', 'Cylinder']],
    body: gasData,
    theme: 'striped',
    margin: { left: margin, right: margin },
    headStyles: { fillColor: [0, 80, 130], fontSize: 9 },
    styles: { fontSize: 9, cellPadding: 3 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 10;
  
  if (result.gasConsumption && result.gasConsumption.length > 0) {
    doc.setTextColor(0, 80, 130);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('GAS CONSUMPTION', margin, yPos);
    yPos += 5;
    
    const consumptionData = result.gasConsumption.map(gc => [
      gc.gasName,
      `${Math.round(gc.gasAvailable)} L`,
      `${Math.round(gc.gasRequired)} L`,
      `${Math.round(gc.gasRemaining)} L`,
      `${Math.round(gc.percentUsed)}%`,
      gc.isSufficient ? 'OK' : 'INSUFFICIENT'
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['Gas', 'Available', 'Required', 'Remaining', 'Used', 'Status']],
      body: consumptionData,
      theme: 'striped',
      margin: { left: margin, right: margin },
      headStyles: { fillColor: [0, 80, 130], fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 2 },
      didParseCell: function(data) {
        if (data.column.index === 5 && data.section === 'body') {
          const value = data.cell.raw as string;
          if (value === 'INSUFFICIENT') {
            data.cell.styles.textColor = [200, 0, 0];
            data.cell.styles.fontStyle = 'bold';
          } else {
            data.cell.styles.textColor = [0, 150, 0];
          }
        }
      }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 10;
  }
  
  if (yPos < 240) {
    doc.setTextColor(0, 80, 130);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('SETTINGS', margin, yPos);
    yPos += 5;
    
    const settingsData = [
      ['Circuit', settings.circuit === 'open' ? 'Open Circuit' : 'CCR'],
      ['Gradient Factors', `${settings.gfLow}/${settings.gfHigh}`],
      ['Descent Rate', `${settings.descentRate} ${settings.units === 'metric' ? 'm' : 'ft'}/min`],
      ['Ascent Rate', `${settings.ascentRate} ${settings.units === 'metric' ? 'm' : 'ft'}/min`],
      ['SAC Bottom', `${settings.sacRateBottom} L/min`],
      ['SAC Deco', `${settings.sacRateDeco} L/min`],
      ['Water Type', settings.waterType === 'salt' ? 'Salt Water' : 'Fresh Water'],
      ['Last Stop', `${settings.lastStopDepth} ${settings.units === 'metric' ? 'm' : 'ft'}`],
    ];
    
    autoTable(doc, {
      startY: yPos,
      head: [],
      body: settingsData,
      theme: 'plain',
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 35 },
        1: { cellWidth: 40 }
      },
      tableWidth: 75,
    });
  }
  
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(200);
  doc.setLineWidth(0.3);
  doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
  
  doc.setTextColor(150);
  doc.setFontSize(7);
  doc.text('This dive plan is for reference only. Always verify calculations and follow safe diving practices.', margin, pageHeight - 10);
  doc.text('Erebus Dive Planner', pageWidth - margin, pageHeight - 10, { align: 'right' });
  
  const filename = `dive-plan-${depth}m-${bottomTime}min-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}

export function downloadDivePlanPdf(input: DivePlanPdfInput): void {
  try {
    generateDivePlanPdf(input);
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw error;
  }
}
